load_module /opt/datadog/nginx/modules/ngx_http_datadog_module.so;

worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log /dev/stdout;
  sendfile on;
  keepalive_timeout 65;
  datadog_agent_url http://datadog-agent:8126;
  datadog_tracing on;

  server {
    listen 8080;
    server_name _;

    location / {
      proxy_pass http://appsec-test-api:8000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
