apiVersion: v1
kind: Service
metadata:
  name: appsec-test-api
  namespace: playground
spec:
  type: ClusterIP
  selector:
    app: appsec-test-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
